### ISSUE TITLE
Task1 - Choose 4 datasets for regression & classification URGENT

### ISSUE THREAD

**Issue by Haelium** [Haelium/CS4404-Machine-Learning-Data-Analytics#11]

**Comment by cedivad** [comment]
We are waiting for an answer from the lecturer to decide on the 4th one, the third one is the ny taxis ones. @manjot4 modified it for use with a classifier.

**Comment by Haelium** [comment]
Great, can you upload the modified taxis dataset?

**Comment by Haelium** [comment]
@cedivad did Jorean Beel ever respond to your email?

**Comment by cedivad** [comment]
@manjot4 actually emailed him.

**Comment by Haelium** [comment]
@cedivad 
@manjot4 
We're using the online news popularity dataset (pushed now)
